# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths: ['thamer_experiments/**']
  pull_request:
    branches: [ "main" ]
    paths: ['thamer_experiments/**']

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f thamer_experiments/requirements.txt ]; then pip install -r thamer_experiments/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run json2yaml to convert all files in 'json2yaml_data/input'
      run: |
        python3 thamer_experiments/json2yaml.py -a
    - name: Run jsonld2turtle to convert all files in 'jsonld2turtle_data/input'
      run: |
        python3 thamer_experiments/jsonld2turtle.py -a
    - name: Run turtle2jsonld to convert all files in 'turtle2jsonld_data/input'
      run: |
        python3 thamer_experiments/turtle2jsonld.py -a
    - name: Run yaml2json to convert all files in 'yaml2json_data/input'
      run: |
        python3 thamer_experiments/yaml2json.py -a
    - name: Run yaml2turtle to convert all files in 'yaml2turtle_data/input'
      run: |
        python3 thamer_experiments/yaml2turtle.py -a
    - name: Run jsonvalidator to validate all files in 'jsonvalidator_data'
      run: |
        python3 thamer_experiments/jsonvalidator.py -a
    - name: Run yamlvalidator to validate all files in 'yamlvalidator_data'
      run: |
        python3 thamer_experiments/yamlvalidator.py -a